# Generated by Django 5.0.4 on 2024-04-15 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0004_auto_20201124_0614"),
        ("staffs", "0002_auto_20201124_0614"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="staff_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("finance", "Finance"),
                ],
                default="admin",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="corecode.subject",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="gender",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("finance", "Finance"),
                ],
                default="male",
                max_length=10,
            ),
        ),
    ]
