# Generated by Django 5.0.4 on 2024-04-15 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0004_alter_staff_gender"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Staff",
        ),
    ]
